#!/usr/bin/env python3
"""
NetSuite SuiteQL Schema Lookup

Explore NetSuite table schemas, column definitions, and relationships.
Reads from cached JSON files (~/.cache/netsuite-schema/) generated by:
  - schema_refresh.py (ODBC full schema — all tables/columns/FKs)
  - refresh-custom subcommand (SuiteQL custom records/fields via gateway)

Falls back gracefully when cache is unavailable:
  L1: ODBC cache (tables.json + columns.json + fkeys.json)
  L2: Custom cache (custom_records.json + custom_fields.json)
  L3: Real-time SuiteQL probe (SELECT * WHERE ROWNUM=1 to discover columns)
  L4: Error message with setup instructions

Usage:
  python3 schema_lookup.py describe <TABLE> [--env sb2] [--format table|json|csv]
  python3 schema_lookup.py tables [PATTERN] [--env sb2]
  python3 schema_lookup.py search <PATTERN> [--env sb2]
  python3 schema_lookup.py relationships <TABLE> [--env sb2]
  python3 schema_lookup.py refresh-custom [--env sb2] [--account twx]
  python3 schema_lookup.py status [--env sb2] [--account twx]
"""

import sys
import os
import json
import fnmatch
import re
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any, Tuple

# Cache root directory
CACHE_ROOT = os.path.expanduser('~/.cache/netsuite-schema')

# Reuse aliases from query_netsuite.py
ACCOUNT_ALIASES = {
    'twx': 'twistedx',
    'twisted': 'twistedx',
    'twistedx': 'twistedx',
    'dm': 'dutyman',
    'duty': 'dutyman',
    'dutyman': 'dutyman'
}

ENV_ALIASES = {
    'prod': 'production',
    'production': 'production',
    'sb1': 'sandbox',
    'sandbox': 'sandbox',
    'sandbox1': 'sandbox',
    'sb2': 'sandbox2',
    'sandbox2': 'sandbox2'
}

DEFAULT_ACCOUNT = 'twistedx'
DEFAULT_ENVIRONMENT = 'sandbox2'

# All valid account/environment combinations
ACCOUNT_ENVIRONMENTS = {
    'twistedx': ['production', 'sandbox', 'sandbox2'],
    'dutyman': ['production', 'sandbox']
}


def resolve_account(account: str) -> str:
    return ACCOUNT_ALIASES.get(account.lower(), account.lower())


def resolve_environment(environment: str) -> str:
    return ENV_ALIASES.get(environment.lower(), environment.lower())


def get_cache_dir(account: str, environment: str) -> str:
    """Get cache directory for a specific account/environment."""
    return os.path.join(CACHE_ROOT, account, environment)


def load_cache(cache_dir: str, filename: str) -> Optional[Dict[str, Any]]:
    """Load a JSON cache file. Returns None if file doesn't exist or is corrupt."""
    path = os.path.join(cache_dir, filename)
    if not os.path.exists(path):
        return None
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def save_cache(cache_dir: str, filename: str, data: Dict[str, Any]) -> None:
    """Save data to a JSON cache file."""
    os.makedirs(cache_dir, exist_ok=True)
    path = os.path.join(cache_dir, filename)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)


def cache_age_days(cache_dir: str) -> Dict[str, Optional[float]]:
    """Return age in days for each cache file."""
    files = ['tables.json', 'columns.json', 'fkeys.json', 'custom_records.json', 'custom_fields.json']
    ages = {}
    for fname in files:
        path = os.path.join(cache_dir, fname)
        if os.path.exists(path):
            mtime = os.path.getmtime(path)
            age = (datetime.now(timezone.utc).timestamp() - mtime) / 86400
            ages[fname] = round(age, 1)
        else:
            ages[fname] = None
    return ages


def matches_pattern(text: str, pattern: str) -> bool:
    """Match text against a glob pattern or substring (case-insensitive)."""
    if not pattern:
        return True
    t = text.lower()
    p = pattern.lower()
    # Glob pattern
    if '*' in p or '?' in p:
        return fnmatch.fnmatch(t, p)
    # Substring match
    return p in t


def _col_width(rows: List[str], header: str, max_width: int = 50) -> int:
    """Compute column width from data + header."""
    w = len(header)
    for r in rows:
        w = max(w, len(str(r)))
    return min(w, max_width)


def format_table_rows(headers: List[str], rows: List[List[str]], max_col: int = 50) -> str:
    """Format rows as an ASCII table."""
    widths = [_col_width([r[i] for r in rows], h, max_col) for i, h in enumerate(headers)]
    sep = '+' + '+'.join('-' * (w + 2) for w in widths) + '+'
    def fmt_row(cells: List[str]) -> str:
        parts = []
        for i, cell in enumerate(cells):
            cell_str = str(cell or '')
            if len(cell_str) > widths[i]:
                cell_str = cell_str[:widths[i] - 1] + '…'
            parts.append(f' {cell_str:<{widths[i]}} ')
        return '|' + '|'.join(parts) + '|'
    lines = [sep, fmt_row(headers), sep]
    for row in rows:
        lines.append(fmt_row(row))
    lines.append(sep)
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Describe
# ---------------------------------------------------------------------------

def describe_table(table_name: str, account: str, environment: str, fmt: str = 'table') -> str:
    """
    Describe columns, types, and FK relationships for a table.
    Merges ODBC cache (primary) with custom field labels (enrichment).
    Falls back to custom cache or real-time probe if ODBC cache unavailable.
    """
    cache_dir = get_cache_dir(account, environment)
    cols_data = load_cache(cache_dir, 'columns.json')
    fkeys_data = load_cache(cache_dir, 'fkeys.json')
    custom_fields_data = load_cache(cache_dir, 'custom_fields.json')

    # Find table in ODBC columns cache (case-insensitive)
    odbc_columns = None
    canonical_table = table_name
    if cols_data:
        for key in cols_data.get('columns', {}):
            if key.lower() == table_name.lower():
                canonical_table = key
                odbc_columns = cols_data['columns'][key]
                break

    # Build label map from custom fields (enrichment)
    label_map: Dict[str, str] = {}
    if custom_fields_data:
        for rec_key, fields in custom_fields_data.get('custom_fields', {}).items():
            if rec_key.lower() == table_name.lower():
                for f in fields:
                    sid = f.get('scriptid', '').lower()
                    label = f.get('label', '')
                    if sid and label:
                        label_map[sid] = label

    source_parts = []
    columns_to_show = []  # List of dicts: {name, type, length, description}

    if odbc_columns:
        # Build column list from ODBC cache
        odbc_refreshed = cols_data.get('_refreshed_at', 'unknown')[:10]
        source_parts.append(f'ODBC cache ({odbc_refreshed})')
        for c in odbc_columns:
            name = c.get('column_name', '')
            label = label_map.get(name.lower(), '')
            description = c.get('description') or label or ''
            columns_to_show.append({
                'name': name,
                'type': c.get('data_type', ''),
                'length': str(c.get('length', '') or ''),
                'description': description
            })

    elif table_name.lower().startswith('customrecord_') and custom_fields_data:
        # L2: custom cache for custom record types
        rec_fields = None
        for rec_key, fields in custom_fields_data.get('custom_fields', {}).items():
            if rec_key.lower() == table_name.lower():
                canonical_table = rec_key
                rec_fields = fields
                break
        if rec_fields:
            cf_refreshed = custom_fields_data.get('_refreshed_at', 'unknown')[:10]
            source_parts.append(f'Custom field cache ({cf_refreshed})')
            # Standard custom record columns always present
            for name in ['ID', 'Name', 'Created', 'LastModified', 'Owner', 'ExternalID']:
                columns_to_show.append({'name': name, 'type': '', 'length': '', 'description': ''})
            for f in rec_fields:
                columns_to_show.append({
                    'name': f.get('scriptid', ''),
                    'type': f.get('field_type', ''),
                    'length': '',
                    'description': f.get('label', '')
                })

    else:
        # L3: real-time probe
        probe = _probe_table(table_name, account, environment)
        if probe.get('error'):
            return f"ERROR: Table '{table_name}' not found in cache or via live query.\n{probe['error']}\n\nRun: python3 schema_refresh.py --account {account} --env {environment}\nor: python3 schema_lookup.py refresh-custom --account {account} --env {environment}"
        source_parts.append('real-time probe (column names only — no types)')
        for col_name in probe.get('columns', []):
            columns_to_show.append({'name': col_name, 'type': '', 'length': '', 'description': ''})

    if custom_fields_data and odbc_columns:
        cf_refreshed = custom_fields_data.get('_refreshed_at', 'unknown')[:10]
        source_parts.append(f'custom field labels ({cf_refreshed})')

    source = ' + '.join(source_parts) if source_parts else 'unknown'

    # Build FK info
    fk_outbound: List[Dict] = []
    fk_inbound: List[Dict] = []
    pk_cols: List[str] = []
    if fkeys_data:
        for fk in fkeys_data.get('foreign_keys', []):
            if fk.get('fk_table', '').lower() == canonical_table.lower():
                fk_outbound.append(fk)
            elif fk.get('pk_table', '').lower() == canonical_table.lower():
                fk_inbound.append(fk)
        for pk in fkeys_data.get('primary_keys', []):
            if pk.get('table_name', '').lower() == canonical_table.lower():
                pk_cols.append(pk.get('column_name', ''))

    # Enrich column descriptions with FK info
    fk_out_map: Dict[str, str] = {}
    for fk in fk_outbound:
        fk_out_map[fk.get('fk_column', '').lower()] = f"→ {fk.get('pk_table', '')}.{fk.get('pk_column', '')}"

    col_count = len(columns_to_show)
    header = f"[{account}/{environment}] Table: {canonical_table} ({col_count} column{'s' if col_count != 1 else ''})\nSource: {source}\n"

    if fmt == 'json':
        result = {
            'table': canonical_table,
            'account': account,
            'environment': environment,
            'source': source,
            'columns': columns_to_show,
            'foreign_keys': {'outbound': fk_outbound, 'inbound': fk_inbound},
            'primary_keys': pk_cols
        }
        return header + json.dumps(result, indent=2)

    if fmt == 'csv':
        lines = ['Column Name,Type,Length,Description,FK Reference']
        for c in columns_to_show:
            fk_ref = fk_out_map.get(c['name'].lower(), '')
            lines.append(f"{c['name']},{c['type']},{c['length']},{c['description']},{fk_ref}")
        return '\n'.join(lines)

    # Table format
    rows = []
    for c in columns_to_show:
        fk_ref = fk_out_map.get(c['name'].lower(), '')
        desc = c['description']
        if fk_ref and not desc:
            desc = fk_ref
        elif fk_ref:
            desc = f"{desc}  {fk_ref}"
        rows.append([c['name'], c['type'], c['length'], desc])

    output = header
    output += format_table_rows(['Column Name', 'Type', 'Length', 'Description / FK'], rows)

    if fk_outbound:
        output += '\n\nOutbound FK (this table → other):'
        for fk in sorted(fk_outbound, key=lambda x: x.get('fk_column', '')):
            output += f"\n  {fk.get('fk_column')} → {fk.get('pk_table')}.{fk.get('pk_column')}"

    if fk_inbound:
        output += '\n\nInbound FK (other tables → this):'
        for fk in sorted(fk_inbound, key=lambda x: x.get('fk_table', '')):
            output += f"\n  {fk.get('fk_table')}.{fk.get('fk_column')} → {canonical_table}.{fk.get('pk_column')}"

    if pk_cols:
        output += f'\n\nPrimary Key: {", ".join(pk_cols)}'

    return output


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------

def list_tables(pattern: Optional[str], account: str, environment: str, fmt: str = 'table') -> str:
    """List tables matching a pattern from the ODBC tables cache."""
    cache_dir = get_cache_dir(account, environment)
    tables_data = load_cache(cache_dir, 'tables.json')
    custom_records_data = load_cache(cache_dir, 'custom_records.json')

    results = []

    if tables_data:
        refreshed = tables_data.get('_refreshed_at', 'unknown')[:10]
        for t in tables_data.get('tables', []):
            name = t.get('table_name', '')
            if not pattern or matches_pattern(name, pattern):
                results.append({
                    'table_name': name,
                    'custom': 'Yes' if t.get('is_custom') else 'No',
                    'hidden': 'Yes' if t.get('is_hidden') else 'No',
                    'description': t.get('description', '')
                })
        source = f'ODBC cache ({refreshed})'
    elif custom_records_data:
        refreshed = custom_records_data.get('_refreshed_at', 'unknown')[:10]
        for r in custom_records_data.get('custom_record_types', []):
            name = r.get('scriptid', '')
            if not pattern or matches_pattern(name, pattern):
                results.append({
                    'table_name': name,
                    'custom': 'Yes',
                    'hidden': 'No',
                    'description': r.get('name', '')
                })
        source = f'custom records cache ({refreshed}) — standard tables not available (run schema_refresh.py for full schema)'
    else:
        return (f"No table cache found for {account}/{environment}.\n\n"
                f"To populate:\n"
                f"  Full schema: python3 schema_refresh.py --account {account} --env {environment}\n"
                f"  Custom only: python3 schema_lookup.py refresh-custom --account {account} --env {environment}")

    total = len(results)
    ptn_str = f' matching "{pattern}"' if pattern else ''
    header = f"[{account}/{environment}] Tables{ptn_str} ({total} result{'s' if total != 1 else ''})\nSource: {source}\n"

    if fmt == 'json':
        return header + json.dumps(results, indent=2)

    if fmt == 'csv':
        lines = ['Table Name,Custom,Hidden,Description']
        for r in results:
            lines.append(f"{r['table_name']},{r['custom']},{r['hidden']},{r['description']}")
        return '\n'.join(lines)

    rows = [[r['table_name'], r['custom'], r['hidden'], r['description']] for r in results]
    return header + format_table_rows(['Table Name', 'Custom', 'Hidden', 'Description'], rows)


# ---------------------------------------------------------------------------
# Search
# ---------------------------------------------------------------------------

def search_schema(pattern: str, account: str, environment: str, fmt: str = 'table') -> str:
    """Search table names and column names/descriptions for a pattern."""
    if not pattern:
        return "ERROR: search requires a pattern argument"

    cache_dir = get_cache_dir(account, environment)
    tables_data = load_cache(cache_dir, 'tables.json')
    cols_data = load_cache(cache_dir, 'columns.json')
    custom_records_data = load_cache(cache_dir, 'custom_records.json')
    custom_fields_data = load_cache(cache_dir, 'custom_fields.json')

    table_matches = []
    col_matches = []

    # Search tables
    if tables_data:
        for t in tables_data.get('tables', []):
            name = t.get('table_name', '')
            desc = t.get('description', '')
            if matches_pattern(name, pattern) or matches_pattern(desc, pattern):
                table_matches.append({'table': name, 'description': desc, 'custom': 'Yes' if t.get('is_custom') else 'No'})
    elif custom_records_data:
        for r in custom_records_data.get('custom_record_types', []):
            name = r.get('scriptid', '')
            label = r.get('name', '')
            if matches_pattern(name, pattern) or matches_pattern(label, pattern):
                table_matches.append({'table': name, 'description': label, 'custom': 'Yes'})

    # Search columns
    if cols_data:
        for tname, cols in cols_data.get('columns', {}).items():
            for c in cols:
                cname = c.get('column_name', '')
                desc = c.get('description', '')
                if matches_pattern(cname, pattern) or matches_pattern(desc, pattern):
                    col_matches.append({'table': tname, 'column': cname, 'type': c.get('data_type', ''), 'description': desc})
    elif custom_fields_data:
        for rec, fields in custom_fields_data.get('custom_fields', {}).items():
            for f in fields:
                sid = f.get('scriptid', '')
                label = f.get('label', '')
                if matches_pattern(sid, pattern) or matches_pattern(label, pattern):
                    col_matches.append({'table': rec, 'column': sid, 'type': f.get('field_type', ''), 'description': label})

    total = len(table_matches) + len(col_matches)
    header = f"[{account}/{environment}] Search results for \"{pattern}\" ({total} result{'s' if total != 1 else ''})\n"

    if fmt == 'json':
        return header + json.dumps({'tables': table_matches, 'columns': col_matches}, indent=2)

    lines = [header]
    if table_matches:
        lines.append(f"TABLES ({len(table_matches)}):")
        rows = [[m['table'], m['custom'], m['description']] for m in table_matches]
        lines.append(format_table_rows(['Table Name', 'Custom', 'Description'], rows))
    if col_matches:
        if table_matches:
            lines.append('')
        lines.append(f"COLUMNS ({len(col_matches)}):")
        rows = [[m['table'], m['column'], m['type'], m['description']] for m in col_matches]
        lines.append(format_table_rows(['Table', 'Column', 'Type', 'Description'], rows))
    if not table_matches and not col_matches:
        lines.append(f"No results found for \"{pattern}\".")

    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Relationships
# ---------------------------------------------------------------------------

def show_relationships(table_name: str, account: str, environment: str, fmt: str = 'table') -> str:
    """Show FK relationships for a table (outbound + inbound)."""
    cache_dir = get_cache_dir(account, environment)
    fkeys_data = load_cache(cache_dir, 'fkeys.json')

    if not fkeys_data:
        return (f"No FK cache found for {account}/{environment}.\n"
                f"Run: python3 schema_refresh.py --account {account} --env {environment}")

    canonical = table_name
    # Try to match case from a known table name in fkeys
    all_tables = set()
    for fk in fkeys_data.get('foreign_keys', []):
        all_tables.add(fk.get('fk_table', ''))
        all_tables.add(fk.get('pk_table', ''))
    for pk in fkeys_data.get('primary_keys', []):
        all_tables.add(pk.get('table_name', ''))
    for t in all_tables:
        if t.lower() == table_name.lower():
            canonical = t
            break

    outbound = [fk for fk in fkeys_data.get('foreign_keys', []) if fk.get('fk_table', '').lower() == canonical.lower()]
    inbound = [fk for fk in fkeys_data.get('foreign_keys', []) if fk.get('pk_table', '').lower() == canonical.lower()]
    pk_cols = [pk.get('column_name', '') for pk in fkeys_data.get('primary_keys', []) if pk.get('table_name', '').lower() == canonical.lower()]

    refreshed = fkeys_data.get('_refreshed_at', 'unknown')[:10]
    header = f"[{account}/{environment}] Relationships for: {canonical}\nSource: ODBC cache ({refreshed})\n"

    if fmt == 'json':
        return header + json.dumps({
            'table': canonical,
            'primary_keys': pk_cols,
            'outbound': outbound,
            'inbound': inbound
        }, indent=2)

    lines = [header]
    if pk_cols:
        lines.append(f"Primary Key: {', '.join(pk_cols)}\n")

    if outbound:
        lines.append(f"Outbound FK ({canonical} → other tables) [{len(outbound)}]:")
        rows = [[fk.get('fk_column', ''), fk.get('pk_table', ''), fk.get('pk_column', '')] for fk in sorted(outbound, key=lambda x: x.get('fk_column', ''))]
        lines.append(format_table_rows(['Column', 'References Table', 'References Column'], rows))
    else:
        lines.append("No outbound foreign keys.")

    lines.append('')

    if inbound:
        lines.append(f"Inbound FK (other tables → {canonical}) [{len(inbound)}]:")
        rows = [[fk.get('fk_table', ''), fk.get('fk_column', ''), fk.get('pk_column', '')] for fk in sorted(inbound, key=lambda x: x.get('fk_table', ''))]
        lines.append(format_table_rows(['From Table', 'From Column', 'This Column'], rows))
    else:
        lines.append("No inbound foreign keys.")

    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Refresh Custom
# ---------------------------------------------------------------------------

def refresh_custom(account: str, environment: str) -> str:
    """Refresh custom records and custom fields via SuiteQL gateway (no ODBC needed)."""
    # Import execute_query from query_netsuite.py (same directory)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)

    try:
        from query_netsuite import execute_query
    except ImportError as e:
        return f"ERROR: Could not import query_netsuite.py: {e}"

    cache_dir = get_cache_dir(account, environment)
    ts = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

    print(f"Refreshing custom schema for {account}/{environment}...")

    # Query custom record types
    # Note: CustomRecordType uses 'internalid' (not 'id'), 'scriptid', 'name', 'isinactive'
    print("  Querying CustomRecordType...")
    crt_result = execute_query(
        "SELECT internalid, scriptid, name, isinactive FROM CustomRecordType WHERE isinactive = 'F' ORDER BY name",
        account=account,
        environment=environment,
        return_all_rows=True
    )
    if crt_result.get('error'):
        return f"ERROR querying CustomRecordType: {crt_result['error']}"

    custom_records = []
    for r in crt_result.get('records', []):
        custom_records.append({
            'id': r.get('internalid'),
            'scriptid': (r.get('scriptid') or '').lower(),
            'name': r.get('name') or ''
        })

    print(f"  Found {len(custom_records)} custom record types")

    # Query custom record fields (fieldtype = 'RECORD' = body fields on custom record types)
    # Join with CustomRecordType to get the record's scriptid for grouping
    # Note: 'name' = field label, 'fieldvaluetype' = data type, 'recordtype' = parent record internalid
    print("  Querying CustomField (custom record fields)...")
    cf_result = execute_query(
        """SELECT cf.id, cf.scriptid, cf.name AS label, cf.fieldvaluetype, crt.scriptid AS record_scriptid
           FROM CustomField cf
           INNER JOIN CustomRecordType crt ON cf.recordtype = crt.internalid
           WHERE cf.fieldtype = 'RECORD' AND crt.isinactive = 'F'
           ORDER BY crt.scriptid, cf.name""",
        account=account,
        environment=environment,
        return_all_rows=True
    )
    if cf_result.get('error'):
        return f"ERROR querying CustomField: {cf_result['error']}"

    custom_fields_grouped: Dict[str, List[Dict]] = {}
    for r in cf_result.get('records', []):
        applies_to = (r.get('record_scriptid') or '').lower()
        if not applies_to:
            continue
        if applies_to not in custom_fields_grouped:
            custom_fields_grouped[applies_to] = []
        custom_fields_grouped[applies_to].append({
            'id': r.get('id'),
            'scriptid': (r.get('scriptid') or '').lower(),
            'label': r.get('label') or '',
            'field_type': r.get('fieldvaluetype') or '',
            'applies_to': applies_to
        })

    total_fields = sum(len(v) for v in custom_fields_grouped.values())
    print(f"  Found {total_fields} custom fields across {len(custom_fields_grouped)} record types")

    # Save to cache
    save_cache(cache_dir, 'custom_records.json', {
        '_source': 'suiteql',
        '_refreshed_at': ts,
        '_account': account,
        '_environment': environment,
        '_record_count': len(custom_records),
        'custom_record_types': custom_records
    })

    save_cache(cache_dir, 'custom_fields.json', {
        '_source': 'suiteql',
        '_refreshed_at': ts,
        '_account': account,
        '_environment': environment,
        '_record_count': total_fields,
        'custom_fields': custom_fields_grouped
    })

    # Update metadata
    metadata = load_cache(cache_dir, '_metadata.json') or {'account': account, 'environment': environment}
    metadata['custom_refresh'] = {
        'timestamp': ts,
        'custom_record_types_count': len(custom_records),
        'custom_fields_count': total_fields
    }
    save_cache(cache_dir, '_metadata.json', metadata)

    return (f"\nDone. Cached to {cache_dir}/\n"
            f"  custom_records.json: {len(custom_records)} record types\n"
            f"  custom_fields.json: {total_fields} fields across {len(custom_fields_grouped)} record types")


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def show_status(account: str, environment: str) -> str:
    """Show cache freshness and record counts for an account/environment."""
    cache_dir = get_cache_dir(account, environment)
    ages = cache_age_days(cache_dir)
    metadata = load_cache(cache_dir, '_metadata.json') or {}

    lines = [f"[{account}/{environment}] Schema Cache Status", f"Cache dir: {cache_dir}\n"]

    for fname, age in ages.items():
        if age is None:
            lines.append(f"  {fname:<30} NOT PRESENT")
        else:
            warn = ' ⚠️  (>90 days)' if age > 90 else ''
            lines.append(f"  {fname:<30} {age} days old{warn}")

    odbc_info = metadata.get('odbc_refresh', {})
    if odbc_info:
        lines.append(f"\nODBC refresh: {odbc_info.get('timestamp', 'unknown')[:10]}")
        lines.append(f"  Tables: {odbc_info.get('tables_count', '?')}, Columns: {odbc_info.get('columns_count', '?')}, FKs: {odbc_info.get('fkeys_count', '?')}")

    custom_info = metadata.get('custom_refresh', {})
    if custom_info:
        lines.append(f"\nCustom refresh: {custom_info.get('timestamp', 'unknown')[:10]}")
        lines.append(f"  Record types: {custom_info.get('custom_record_types_count', '?')}, Fields: {custom_info.get('custom_fields_count', '?')}")

    if not odbc_info and not custom_info:
        lines.append("\nNo cache populated yet.")
        lines.append("Run: python3 schema_refresh.py --account " + account + " --env " + environment)
        lines.append("or:  python3 schema_lookup.py refresh-custom --account " + account + " --env " + environment)

    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Real-time probe (L3 fallback)
# ---------------------------------------------------------------------------

def _probe_table(table_name: str, account: str, environment: str) -> Dict[str, Any]:
    """Probe a table's columns via SELECT * WHERE ROWNUM = 1."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)

    try:
        from query_netsuite import execute_query
    except ImportError as e:
        return {'error': f"Cannot import query_netsuite.py: {e}", 'columns': []}

    # Try to get at least one row to discover column names
    result = execute_query(
        f"SELECT * FROM {table_name} WHERE ROWNUM <= 1",
        account=account,
        environment=environment
    )
    if result.get('error'):
        return {'error': result['error'], 'columns': []}

    records = result.get('records', [])
    if records:
        return {'columns': list(records[0].keys()), 'error': None}

    # Table exists but is empty — get columns via a different approach
    # Try forcing a column error to see what's available (NetSuite sometimes reveals column list in errors)
    return {'columns': [], 'error': None, 'note': 'Table exists but is empty (no column metadata available)'}


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------

def parse_args(argv: List[str]) -> Dict[str, Any]:
    """Parse command-line arguments."""
    args = {
        'subcommand': None,
        'target': None,
        'pattern': None,
        'account': DEFAULT_ACCOUNT,
        'environment': DEFAULT_ENVIRONMENT,
        'format': 'table',
        'error': None
    }

    if len(argv) < 2:
        args['error'] = 'missing subcommand'
        return args

    args['subcommand'] = argv[1].lower()

    # Positional argument (table name or pattern)
    i = 2
    if i < len(argv) and not argv[i].startswith('--'):
        args['target'] = argv[i]
        i += 1

    # Named options
    while i < len(argv):
        arg = argv[i]
        if arg in ('--account',) and i + 1 < len(argv):
            args['account'] = argv[i + 1]
            i += 2
        elif arg in ('--env', '--environment') and i + 1 < len(argv):
            args['environment'] = argv[i + 1]
            i += 2
        elif arg in ('--format',) and i + 1 < len(argv):
            args['format'] = argv[i + 1]
            i += 2
        else:
            i += 1

    return args


USAGE = """
NetSuite SuiteQL Schema Lookup

Usage:
  python3 schema_lookup.py describe <TABLE> [options]
  python3 schema_lookup.py tables [PATTERN] [options]
  python3 schema_lookup.py search <PATTERN> [options]
  python3 schema_lookup.py relationships <TABLE> [options]
  python3 schema_lookup.py refresh-custom [options]
  python3 schema_lookup.py status [options]

Options:
  --account <twx|dm>            Account (default: twistedx)
  --env <prod|sb1|sb2>          Environment (default: sandbox2)
  --format <table|json|csv>     Output format (default: table)

Subcommands:
  describe <TABLE>      Show all columns, types, FKs for a table
  tables [PATTERN]      List tables (glob pattern optional, e.g. "custom*")
  search <PATTERN>      Search table names and column names
  relationships <TABLE> Show FK graph for a table
  refresh-custom        Pull CustomRecordType + CustomField from gateway
  status                Show cache age and record counts

Examples:
  python3 schema_lookup.py describe Transaction --env sb2
  python3 schema_lookup.py tables "custom*" --env sb2
  python3 schema_lookup.py search "shipping" --env sb2
  python3 schema_lookup.py relationships Transaction --env sb2
  python3 schema_lookup.py refresh-custom --account twx --env sb2
  python3 schema_lookup.py status
"""


def main():
    args = parse_args(sys.argv)
    account = resolve_account(args['account'])
    environment = resolve_environment(args['environment'])
    fmt = args['format']

    if args['error'] or args['subcommand'] in (None, 'help', '--help', '-h'):
        print(USAGE)
        sys.exit(0 if not args['error'] else 1)

    sub = args['subcommand']
    target = args['target']

    if sub == 'describe':
        if not target:
            print("ERROR: describe requires a table name\nUsage: python3 schema_lookup.py describe <TABLE>")
            sys.exit(1)
        print(describe_table(target, account, environment, fmt))

    elif sub == 'tables':
        print(list_tables(target, account, environment, fmt))

    elif sub == 'search':
        if not target:
            print("ERROR: search requires a pattern\nUsage: python3 schema_lookup.py search <PATTERN>")
            sys.exit(1)
        print(search_schema(target, account, environment, fmt))

    elif sub == 'relationships':
        if not target:
            print("ERROR: relationships requires a table name\nUsage: python3 schema_lookup.py relationships <TABLE>")
            sys.exit(1)
        print(show_relationships(target, account, environment, fmt))

    elif sub == 'refresh-custom':
        result = refresh_custom(account, environment)
        print(result)

    elif sub == 'status':
        if target:
            # Show status for all accounts/environments if "all" passed
            if target.lower() == 'all':
                for acct, envs in ACCOUNT_ENVIRONMENTS.items():
                    for env in envs:
                        print(show_status(acct, env))
                        print()
                return
        print(show_status(account, environment))

    else:
        print(f"ERROR: Unknown subcommand '{sub}'\n{USAGE}")
        sys.exit(1)


if __name__ == '__main__':
    main()
